<a href="https://www.kaggle.com/code/mohammadfaizanraza/data-c-t-p2?scriptVersionId=132530786" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("/kaggle/input/data-science-job-posting-on-glassdoor/Uncleaned_DS_jobs.csv")

In [3]:
df.drop('index', inplace=True, axis=1)
df.head()

Job Title               Salary Estimate  \
0  Sr Data Scientist  $137K-$171K (Glassdoor est.)   
1     Data Scientist  $137K-$171K (Glassdoor est.)   
2     Data Scientist  $137K-$171K (Glassdoor est.)   
3     Data Scientist  $137K-$171K (Glassdoor est.)   
4     Data Scientist  $137K-$171K (Glassdoor est.)   

                                     Job Description  Rating  \
0  Description\n\nThe Senior Data Scientist is re...     3.1   
1  Secure our Nation, Ignite your Future\n\nJoin ...     4.2   
2  Overview\n\n\nAnalysis Group is one of the lar...     3.8   
3  JOB DESCRIPTION:\n\nDo you have a passion for ...     3.5   
4  Data Scientist\nAffinity Solutions / Marketing...     2.9   

              Company Name       Location            Headquarters  \
0         Healthfirst\n3.1   New York, NY            New York, NY   
1             ManTech\n4.2  Chantilly, VA             Herndon, VA   
2      Analysis Group\n3.8     Boston, MA              Boston, MA   
3             INFICON\n3.5     Newton, MA  Bad Ragaz, Switzerland   
4  Affinity Solutions\n2.9   New York, NY            New York, NY   

                      Size  Founded        Type of ownership  \
0   1001 to 5000 employees     1993   Nonprofit Organization   
1  5001 to 10000 employees     1968         Company - Public   
2   1001 to 5000 employees     1981  Private Practice / Firm   
3    501 to 1000 employees     2000         Company - Public   
4      51 to 200 employees     1998        Company - Private   

                                Industry             Sector  \
0                     Insurance Carriers          Insurance   
1                 Research & Development  Business Services   
2                             Consulting  Business Services   
3  Electrical & Electronic Manufacturing      Manufacturing   
4                Advertising & Marketing  Business Services   

                      Revenue  \
0    Unknown / Non-Applicable   
1      $1 to $2 billion (USD)   
2  $100 to $500 million (USD)   
3  $100 to $500 million (USD)   
4    Unknown / Non-Applicable   

                                         Competitors  
0            EmblemHealth, UnitedHealth Group, Aetna  
1                                                 -1  
2                                                 -1  
3  MKS Instruments, Pfeiffer Vacuum, Agilent Tech...  
4               Commerce Signals, Cardlytics, Yodlee

In [4]:
df['Salary Estimate'].unique()

array(['$137K-$171K (Glassdoor est.)', '$75K-$131K (Glassdoor est.)',
       '$79K-$131K (Glassdoor est.)', '$99K-$132K (Glassdoor est.)',
       '$90K-$109K (Glassdoor est.)', '$101K-$165K (Glassdoor est.)',
       '$56K-$97K (Glassdoor est.)', '$79K-$106K (Glassdoor est.)',
       '$71K-$123K (Glassdoor est.)', '$90K-$124K (Glassdoor est.)',
       '$91K-$150K (Glassdoor est.)', '$141K-$225K (Glassdoor est.)',
       '$145K-$225K(Employer est.)', '$79K-$147K (Glassdoor est.)',
       '$122K-$146K (Glassdoor est.)', '$112K-$116K (Glassdoor est.)',
       '$110K-$163K (Glassdoor est.)', '$124K-$198K (Glassdoor est.)',
       '$79K-$133K (Glassdoor est.)', '$69K-$116K (Glassdoor est.)',
       '$31K-$56K (Glassdoor est.)', '$95K-$119K (Glassdoor est.)',
       '$212K-$331K (Glassdoor est.)', '$66K-$112K (Glassdoor est.)',
       '$128K-$201K (Glassdoor est.)', '$138K-$158K (Glassdoor est.)',
       '$80K-$132K (Glassdoor est.)', '$87K-$141K (Glassdoor est.)',
       '$92K-$155K (Glassdo

In [5]:
df['Salary Estimate'] = df['Salary Estimate'].str.split('(').str[0]
df['Salary Estimate'] = df['Salary Estimate'].str.replace('K', '').str.replace('$', '')
df[['min_salary', 'max_salary']] = df['Salary Estimate'].str.split('-', expand=True).astype(int)

/tmp/ipykernel_20/4276175829.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Salary Estimate'] = df['Salary Estimate'].str.replace('K', '').str.replace('$', '')


In [6]:
df["min_salary"].unique()

array([137,  75,  79,  99,  90, 101,  56,  71,  91, 141, 145, 122, 112,
       110, 124,  69,  31,  95, 212,  66, 128, 138,  80,  87,  92, 105])

In [7]:
df["max_salary"].unique()

array([171, 131, 132, 109, 165,  97, 106, 123, 124, 150, 225, 147, 146,
       116, 163, 198, 133,  56, 119, 331, 112, 201, 158, 141, 155, 167])

In [8]:
df['avg_salary'] = (df['min_salary'] + df['max_salary']) // 2

In [9]:
df["avg_salary"].unique()

array([154, 103, 105, 115,  99, 133,  76,  92,  97, 107, 120, 183, 185,
       113, 134, 114, 136, 161, 106,  43, 271,  89, 164, 148, 123])

In [10]:
df['Company Name'] = df['Company Name'].str.replace('\n.*', '')

/tmp/ipykernel_20/2830926025.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Company Name'] = df['Company Name'].str.replace('\n.*', '')


In [11]:
df['Company Name'].unique()

array(['Healthfirst', 'ManTech', 'Analysis Group', 'INFICON',
       'Affinity Solutions', 'HG Insights', 'Novartis', 'iRobot',
       'Intuit - Data', 'XSELL Technologies', 'Novetta', '1904labs',
       'PNNL', 'Old World Industries', 'Mathematica Policy Research',
       'Guzman & Griffin Technologies (GGTI)', 'Upside Business Travel',
       'Buckman', 'Insight Enterprises, Inc.', 'Tower Health',
       'Triplebyte', 'PulsePoint', 'Exponent', 'Guardian Life',
       'Spectrum Communications and Consulting', 'Oversight Systems',
       'LSQ', 'MIT Lincoln Laboratory', 'Kingfisher Systems', 'Formation',
       'Cohere Health', 'Acuity Insurance', 'Chef', 'Puget Sound Energy',
       'Sandhills Global', 'A Place for Mom', 'Great-Circle Technologies',
       'Edmunds.com', 'Cambridge Associates, LLC',
       'Liberty Mutual Insurance', 'Cenlar', 'Arsenal Biosciences',
       'Eversight', 'Pfizer', 'Klaviyo', 'Intellectual Ventures',
       'GovTech', 'Quick Base', 'Giving Assistant', 'T

In [12]:
df["Rating"].unique()

array([ 3.1,  4.2,  3.8,  3.5,  2.9,  3.9,  4.4,  3.6,  4.5,  4.7,  3.7,
        3.4,  4.1,  3.2,  4.3,  2.8,  5. ,  4.8,  3.3,  2.7,  2.2,  2.6,
        4. ,  2.5,  4.9,  2.4, -1. ,  2.3,  4.6,  3. ,  2.1,  2. ])

In [13]:
import numpy as np
df.Rating = np.where(df.Rating==-1.0,0,df.Rating)

In [14]:
df.loc[df.Rating == -1.0, 'Rating'] = 0

In [15]:
df.sort_values(by='Rating', ascending=False)

Job Title Salary Estimate  \
284                          Data Scientist        141-225    
441                          Data Scientist         79-133    
308                          Data Scientist         145-225   
130                          Data Scientist         90-109    
531                          Data Scientist         66-112    
..                                      ...             ...   
230                          Data Scientist         71-123    
637                          Data Scientist         92-155    
411                          Data Scientist        124-198    
519  Scientist / Group Lead, Cancer Biology        212-331    
290                          Data Scientist        141-225    

                                       Job Description  Rating  \
284  Cohere Health is simplifying healthcare for pa...     5.0   
441  Job Description\nWe are looking for a Data Sci...     5.0   
308  Data Scientist\n\nRequirements\nMS or PhD in C...     5.0   
130  Intro\n\nWhy this job?\n\n1. Work on a product...     5.0   
531  Job Description\nData Scientist – Washington D...     5.0   
..                                                 ...     ...   
230  Senior Data Scientist Active Secret clearance ...     0.0   
637  Job Description\nWorking at Sophinea\n\nSophin...     0.0   
411  Our entertainment company is seeking a Data Sc...     0.0   
519  Scientist / Group Lead, Cancer Biology\nLocati...     0.0   
290  Work Authorization Those authorized to work in...     0.0   

                Company Name           Location       Headquarters  \
284            Cohere Health         Boston, MA         Boston, MA   
441                   Maxiom        Ashburn, VA        Ashburn, VA   
308           Kollasoft Inc.       New York, NY         Irving, TX   
130              Notion Labs  San Francisco, CA  San Francisco, CA   
531             JCD Staffing     Washington, DC     Germantown, MD   
..                       ...                ...                ...   
230             Encode, Inc.        Norfolk, VA      Manalapan, NJ   
637                 Sophinea      Chantilly, VA                 -1   
411                 Evolvinc        Burbank, CA    Los Angeles, CA   
519  Monte Rosa Therapeutics      Cambridge, MA                 -1   
290                 PETADATA  San Francisco, CA        Fremont, CA   

                    Size  Founded  Type of ownership  \
284    1 to 50 employees     2019  Company - Private   
441    1 to 50 employees       -1   Company - Public   
308              Unknown       -1   Company - Public   
130    1 to 50 employees     2016  Company - Private   
531    1 to 50 employees       -1  Company - Private   
..                   ...      ...                ...   
230    1 to 50 employees       -1  Company - Private   
637    1 to 50 employees       -1            Unknown   
411    1 to 50 employees     2005  Company - Private   
519                   -1       -1                 -1   
290  51 to 200 employees       -1  Company - Private   

                                    Industry                  Sector  \
284                              IT Services  Information Technology   
441                                       -1                      -1   
308                                       -1                      -1   
130  Enterprise Software & Network Solutions  Information Technology   
531                                       -1                      -1   
..                                       ...                     ...   
230                              IT Services  Information Technology   
637                                       -1                      -1   
411                              IT Services  Information Technology   
519                                       -1                      -1   
290                                       -1                      -1   

                      Revenue Competitors  min_salary  max_salary  avg_salary  
284  Unknown / Non-Applic

In [16]:
df["Location"].unique()

array(['New York, NY', 'Chantilly, VA', 'Boston, MA', 'Newton, MA',
       'Santa Barbara, CA', 'Cambridge, MA', 'Bedford, MA',
       'San Diego, CA', 'Chicago, IL', 'Herndon, VA', 'Saint Louis, MO',
       'Richland, WA', 'Northbrook, IL', 'Washington, DC', 'Remote',
       'Memphis, TN', 'Plano, TX', 'West Grove, PA', 'Phoenix, AZ',
       'Appleton, WI', 'Atlanta, GA', 'Orlando, FL', 'Lexington, MA',
       'McLean, VA', 'San Francisco, CA', 'Sheboygan, WI',
       'United States', 'Bothell, WA', 'Lincoln, NE', 'Overland Park, KS',
       'Santa Monica, CA', 'Portsmouth, NH', 'Ewing, NJ',
       'South San Francisco, CA', 'Palo Alto, CA', 'Bellevue, WA',
       'New Orleans, LA', 'Akron, OH', 'Fort Wayne, IN', 'Woburn, MA',
       'Carson, CA', 'Coral Gables, FL', 'Santa Clara, CA',
       'Brisbane, CA', 'Winter Park, FL', 'Redwood City, CA',
       'Peoria, IL', 'Ipswich, MA', 'Carmel, IN', 'Emeryville, CA',
       'Gaithersburg, MD', 'Longmont, CO', 'Austin, TX', 'Yakima, WA',
 

In [17]:
df['job_state'] = df['Location'].str.split(',').str[-1].str.strip()

In [18]:
df['same_state'] = (df['Location'] == df['Headquarters']).astype(int)

In [19]:
current_year = 2023
df['company_age'] = current_year - df['Founded'].where(df['Founded'] >= 1, 0)

In [20]:
df["company_age"].unique()

array([  30,   55,   42,   23,   25,   13,   27,   33,   40,    9,   11,
          7,   58,   50,   37,   26,    8,   78,   35,    6,   12,   56,
        163,   31,   20,   72,   18,    4,   98,   15,   24,   45,   57,
        111,   65,   10,  174,  242,   97,   17,   29,  160,   28, 2023,
         41,   49,   22,   38,  110,   52,  112,   14,   64,   16,   84,
         21,   62,   60,   54,   77,   66,   70,   75,  173,  172,   19,
         47,  105,   69,   76,   68,    5,   86,  106,   88,   94,  203,
         71,   91,  129,   63,  235,  193,   39,   90,  143,  136,   53,
         81,   43,   34,  115,  170,  148,  109,  125,   67,   46,   36,
        127,   51,   74,   61])

In [21]:
df[df['company_age']==2023].shape

(118, 20)

In [22]:
df.company_age[df.company_age == 2023] = 0

/tmp/ipykernel_20/1107467767.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.company_age[df.company_age == 2023] = 0


In [23]:
df['Job Description'][2].split('\n')

['Overview',
 '',
 '',
 'Analysis Group is one of the largest international economics consulting firms, with more than 1,000 professionals across 14 offices in North America, Europe, and Asia. Since 1981, we have provided expertise in economics, finance, health care analytics, and strategy to top law firms, Fortune Global 500 companies, and government agencies worldwide. Our internal experts, together with our network of affiliated experts from academia, industry, and government, offer our clients exceptional breadth and depth of expertise.',
 '',
 'We are currently seeking a Data Scientist to join our team. The ideal candidate should be passionate about working on cutting edge research and analytical services for Fortune 500 companies, global pharma/biotech firms and leaders in industries such as finance, energy and life sciences. The Data Scientist will be a contributing member to client engagements and have the opportunity to work with our network of world-class experts and thought 

In [24]:
keywords = ['python', 'excel', 'hadoop', 'spark', 'aws', 'tableau', 'big data']

# Create binary columns for each keyword
for keyword in keywords:
    df[keyword] = df['Job Description'].str.lower().apply(lambda x: 1 if keyword in x else 0)


In [25]:
df.head()

Job Title Salary Estimate  \
0  Sr Data Scientist        137-171    
1     Data Scientist        137-171    
2     Data Scientist        137-171    
3     Data Scientist        137-171    
4     Data Scientist        137-171    

                                     Job Description  Rating  \
0  Description\n\nThe Senior Data Scientist is re...     3.1   
1  Secure our Nation, Ignite your Future\n\nJoin ...     4.2   
2  Overview\n\n\nAnalysis Group is one of the lar...     3.8   
3  JOB DESCRIPTION:\n\nDo you have a passion for ...     3.5   
4  Data Scientist\nAffinity Solutions / Marketing...     2.9   

         Company Name       Location            Headquarters  \
0         Healthfirst   New York, NY            New York, NY   
1             ManTech  Chantilly, VA             Herndon, VA   
2      Analysis Group     Boston, MA              Boston, MA   
3             INFICON     Newton, MA  Bad Ragaz, Switzerland   
4  Affinity Solutions   New York, NY            New York, NY   

                      Size  Founded        Type of ownership  ... job_state  \
0   1001 to 5000 employees     1993   Nonprofit Organization  ...        NY   
1  5001 to 10000 employees     1968         Company - Public  ...        VA   
2   1001 to 5000 employees     1981  Private Practice / Firm  ...        MA   
3    501 to 1000 employees     2000         Company - Public  ...        MA   
4      51 to 200 employees     1998        Company - Private  ...        NY   

  same_state company_age python  excel  hadoop  spark aws  tableau  big data  
0          1          30      0      0       0      0   1        0         0  
1          0          55      0      0       1      0   0        0         1  
2          1          42      1      1       0      0   1        0         0  
3          0          23      1      1       0      0   1        0         0  
4          1          25      1      1       0      0   0        0         0  

[5 rows x 27 columns]

In [26]:
def title_simplifier(title):
    title = title.lower()
    keyword_mapping = {
        'data scientist': 'data scientist',
        'data engineer': 'data engineer',
        'analyst': 'analyst',
        'machine learning': 'mle',
        'manager': 'manager',
        'director': 'director'
    }
    return keyword_mapping.get(title, 'na')

In [27]:
def seniority(title):
    title = title.lower()
    senior_keywords = ['sr', 'senior', 'lead', 'principal']
    if any(keyword in title for keyword in senior_keywords):
        return 'senior'
    elif 'jr' in title:
        return 'jr'
    else:
        return 'na'


In [28]:
df["Seniority"] = df["Job Title"].apply(seniority)

In [29]:
df["Job Title"] = df["Job Title"].apply(title_simplifier)

In [30]:
df = df[~((df['job_state']=='Remote') | (df['job_state']=='Utah') | (df['job_state']=='New Jersey') | (df['job_state']=='Texas') | (df['job_state']=='California'))]
df.job_state = df.job_state.apply(lambda x: x.replace('United States','US'))
df.job_state.value_counts()

CA    165
VA     89
MA     62
NY     52
MD     40
IL     30
DC     26
TX     17
WA     16
OH     14
MO     12
PA     12
US     11
CO     10
NJ     10
NC      9
GA      9
FL      8
TN      8
OK      6
WI      6
IN      5
MI      5
AZ      4
AL      4
MN      4
CT      4
UT      3
NE      3
IA      3
OR      2
SC      2
RI      2
NH      2
LA      1
MS      1
KS      1
DE      1
WV      1
Name: job_state, dtype: int64

In [31]:
df.drop(['Founded','Competitors'], axis=1,inplace=True)